function [Q, q, S, R, r, A, B, gamma, D, E, c, PIPG_c_lower, PIPG_c_upper] = Make_Model(state0, input0, target, Obs_Pos, Obs_r)
    dt = 0.2;m = 2.69; g = 9.81;
    Ixx = 0.015;Iyy = 0.015;Izz = 0.0245;

    StateDim = size(state0,1);
    InputDim = size(input0,1);
    N = size(input0,2);

    x0 = state0(1,:);y0 = state0(2,:);z0 = state0(3,:);
    vx0 = state0(4,:);vy0 = state0(5,:);vz0 = state0(6,:);
    phi0 = state0(7,:);theta0 = state0(8,:);psi0 = state0(9,:);
    omegax0 = state0(10,:);omegay0 = state0(11,:);omegaz0 = state0(12,:);
    F0 = input0(1,:);
    taux0 = input0(2,:);tauy0 = input0(3,:);tauz0 = input0(4,:);

    xT = target(1,:);yT = target(2,:);zT = target(3,:);
    vxT = target(4,:);vyT = target(5,:);vzT = target(6,:);
    phiT = target(7,:);thetaT = target(8,:);psiT = target(9,:);
    omegaxT = target(10,:);omegayT = target(11,:);omegazT = target(12,:);

    Q = zeros(StateDim, StateDim, N+1);
    q = zeros(StateDim, N+1);
    S = zeros(StateDim,InputDim, N);
    R = zeros(InputDim, InputDim, N);
    r = zeros(InputDim, N);
    D = cell(1,N+1);
    E = cell(1,N);
    A = zeros(StateDim, StateDim, N);
    B = zeros(StateDim, InputDim, N);
    gamma = zeros(StateDim, N+1);
    c = cell(1,N+1);
    PIPG_c_lower = -Inf(StateDim*N+InputDim*N,1);
    PIPG_c_upper = Inf(StateDim*N+InputDim*N,1);
    
    for k = 1:N
        Q(:,:,k) = 10 * diag([2,2,2,0.5,0.5,0.5,0.1,0.1,0.1,0.1,0.1,0.1]);
        q(:,k) = Q(:,:,k) * (state0(:,k)-target);  % x_ref是常值吗
        S(:,:,k) = zeros(StateDim,InputDim);
        R(:,:,k) = 5 * eye(InputDim);
        r(:,k) = R(:,:,k) * input0(:,k);

        A(:,:,k) = eye(StateDim) + [zeros(3,3),eye(3),zeros(3,6);...
            zeros(1,6),-F0(k)/m*(-sin(phi0(k))*sin(theta0(k))*cos(psi0(k))+cos(phi0(k))*sin(psi0(k))),-F0(k)/m*cos(phi0(k))*cos(theta0(k))*cos(psi0(k)),-F0(k)/m*(-cos(phi0(k))*sin(theta0(k))*sin(psi0(k))+sin(phi0(k))*cos(psi0(k))),zeros(1,3);...
            zeros(1,6),-F0(k)/m*(-sin(phi0(k))*sin(theta0(k))*sin(psi0(k))-cos(phi0(k))*cos(psi0(k))),-F0(k)/m*cos(phi0(k))*cos(theta0(k))*sin(psi0(k)),-F0(k)/m*(cos(phi0(k))*sin(theta0(k))*cos(psi0(k))+sin(phi0(k))*sin(psi0(k))),zeros(1,3);...
            zeros(1,6),1/m*(m*g+F0(k)*sin(phi0(k))*cos(theta0(k))),1/m*(m*g+F0(k)*cos(phi0(k))*sin(theta0(k))),0,zeros(1,3);... 
            zeros(1,6),omegax0(k)+omegay0(k)*cos(phi0(k))*tan(theta0(k))-omegaz0(k)*sin(phi0(k))*tan(theta0(k)),omegax0(k)+omegay0(k)*sin(phi0(k))/(cos(theta0(k)))^2+omegaz0(k)*cos(phi0(k))/(cos(theta0(k)))^2,0,zeros(1,3);...
            zeros(1,6),-omegay0(k)*sin(phi0(k))-omegaz0(k)*sin(phi0(k)),0,0,zeros(1,3);...
            zeros(1,6),1/cos(theta0(k))*(omegay0(k)*cos(phi0(k))-omegaz0(k)*sin(phi0(k))),sin(theta0(k))/(cos(theta0(k)))^2*(omegay0(k)*sin(phi0(k))+omegaz0(k)*cos(phi0(k))),0,zeros(1,3);...
            zeros(1,9),0,1/Ixx*(taux0(k)+omegaz0(k)*(Iyy-Izz)),1/Ixx*(omegay0(k)*(Iyy-Izz));...
            zeros(1,9),1/Iyy*(tauy0(k)+omegaz0(k)*(Izz-Ixx)),0,1/Iyy*(tauy0(k)+omegax0(k)*(Izz-Ixx));...
            zeros(1,9),1/Izz*(tauz0(k)+omegay0(k)*(Ixx-Iyy)),1/Izz*(tauz0(k)+omegax0(k)*(Ixx-Iyy)),0
            ]*dt;

        B(:,:,k) = [zeros(3,4);...
            -1/m*(cos(phi0(k))*sin(theta0(k))*cos(psi0(k))+sin(phi0(k))*sin(psi0(k))),zeros(1,3);...
            -1/m*(cos(phi0(k))*sin(theta0(k))*sin(psi0(k))-sin(phi0(k))*cos(psi0(k))),zeros(1,3);...
            -1/m*cos(phi0(k))*cos(theta0(k)),zeros(1,3);...
            zeros(3,4);...
            0,1/Ixx,0,0;...
            0,0,1/Iyy,0;...
            0,0,0,1/Izz;...
            ] * dt;
%         D{k} = [
        D{k} = [0,0,0,1,0,0,zeros(1,6);...
            0,0,0,-1,0,0,zeros(1,6);...
            0,0,0,0,1,0,zeros(1,6);...
            0,0,0,0,-1,0,zeros(1,6);...
            0,0,0,0,0,1,zeros(1,6);...
            0,0,0,0,0,-1,zeros(1,6);...
            zeros(8,12)
             ];
        
%         E{k} = [
        E{k} = [zeros(1,4);...
               zeros(1,4);...
               zeros(1,4);...
               zeros(1,4); ...
               zeros(1,4);...
               zeros(1,4);...
               1,0,0,0;...
               -1,0,0,0;...
               0,1,0,0;...
               0,-1,0,0;...
               0,0,1,0;...
               0,0,-1,0;...
               0,0,0,1;...
               0,0,0,-1
             ];
        
%         c{k} = [
        c{k} = [D{k}(1:6,:)*state0(:,k) + 6*(-1.5)*ones(6,1); ...
              E{k}(end-7:end,:)*input0(:,k) + [-30;-30;-1*ones(6,1)]
             ];

        gamma(:,k+1) = [vx0(k);vy0(k);vz0(k);...
                        -1/m*F0(k)*(cos(phi0(k))*sin(theta0(k))*cos(psi0(k))+sin(phi0(k))*sin(psi0(k)));...
                        -1/m*F0(k)*(cos(phi0(k))*sin(theta0(k))*sin(psi0(k))-sin(phi0(k))*cos(psi0(k)));...
                        1/m*(m*g-F0(k)*(cos(phi0(k))*cos(theta0(k))));...
                        omegax0(k)+omegay0(k)*sin(phi0(k)*tan(theta0(k)))+omegaz0(k)*cos(theta0(k))*tan(theta0(k));...
                        omegay0(k)*cos(phi0(k))-omegaz0(k)*sin(phi0(k));...
                        1/cos(theta0(k))*(omegay0(k)*sin(phi0(k))+omegaz0(k)*cos(phi0(k)));...
                        1/Ixx*(taux0(k)+omegay0(k)*omegaz0(k)*(Iyy-Izz));...
                        1/Iyy*(tauy0(k)+omegax0(k)*omegaz0(k)*(Izz-Ixx));...
                        1/Izz*(tauz0(k)+omegax0(k)*omegay0(k)*(Ixx-Iyy))
                       ] * dt + state0(:,k) - state0(:,k+1);
        if k == 1
            PIPG_c_lower(StateDim*N+InputDim*(k-1)+1:StateDim*N+InputDim*k) = -input0(:,k) - [30; 1; 1; 1];
            PIPG_c_upper(StateDim*N+InputDim*(k-1)+1:StateDim*N+InputDim*k) = -input0(:,k) + [30; 1; 1; 1];
        elseif k >= 2
            PIPG_c_lower(StateDim*(k-2)+4:StateDim*(k-2)+6) = -state0(4:6,k) - [1.5; 1.5; 1.5];
            PIPG_c_upper(StateDim*(k-2)+4:StateDim*(k-2)+6) = -state0(4:6,k) + [1.5; 1.5; 1.5];
            PIPG_c_lower(StateDim*N+InputDim*(k-1)+1:StateDim*N+InputDim*k) = -input0(:,k) - [30; 1; 1; 1];
            PIPG_c_upper(StateDim*N+InputDim*(k-1)+1:StateDim*N+InputDim*k) = -input0(:,k) + [30; 1; 1; 1];
        end
    end
%     D{N+1} = [ %去除了避障
    D{N+1} = [1,0,0,0,0,0,zeros(1,6);...
            -1,0,0,0,0,0,zeros(1,6);...
            0,1,0,0,0,0,zeros(1,6);...
            0,-1,0,0,0,0,zeros(1,6);...
            0,0,1,0,0,0,zeros(1,6);...
            0,0,-1,0,0,0,zeros(1,6);...
%                           0                  0       1       0; ...
%                           0                  0      -1       0; ...
%                           0                  0       0       1; ...
%                           0                  0       0      -1
          ];
    
%     c{N+1} = [
    c{N+1} = [D{N+1}(1:end,:)*state0(:,N+1) + [-xT;xT;-yT;yT;-zT;zT] - 0.2
          ];
    PIPG_c_lower(StateDim*(N-1)+4:StateDim*(N-1)+6) = -state0(4:6,N+1) - [1.5; 1.5; 1.5];
    PIPG_c_upper(StateDim*(N-1)+4:StateDim*(N-1)+6) = -state0(4:6,N+1) + [1.5; 1.5; 1.5];
    Q(:,:,N+1) = 10 * diag([2,2,2,0.5,0.5,0.5,0.1,0.1,0.1,0.1,0.1,0.1]);
    q(:,N+1) = Q(:,:,N+1) * (state0(:,N+1)-target);
end